# Generated by Django 3.1.3 on 2020-12-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_autor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado Activo/Inactivo'),
        ),
    ]
