# Generated by Django 3.1.3 on 2021-01-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombres'),
        ),
    ]
