# Generated by Django 3.1.3 on 2021-02-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20210205_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
