# Generated by Django 3.1.3 on 2021-02-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20210213_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
